/*
 * This source file was generated by the Gradle 'init' task
 */
package {{ cookiecutter.group_domain_type }}.{{ cookiecutter.group_name }}

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
